services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq_nestjs

networks:
  rabbitmq_nestjs:
    driver: bridge

volumes:
  rabbitmq_data:
