services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend_nestjs

  mongo:
    image: mongo:7.0
    container_name: 'mongo'
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend_nestjs

networks:
  backend_nestjs:
    driver: bridge

volumes:
  rabbitmq_data:
  mongo_data:
